package com.avodotiiets.string;

import com.avodotiiets.LeetcodeLink;

/**
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 */
@LeetcodeLink("https://leetcode.com/problems/find-the-difference/")
public class FindTheDifference {

    public char findTheDifference(String s, String t) {
        int sourceSum = 0;
        int targetSum = 0;

        int i = 0;

        while (i < Math.min(s.length(), t.length())) {
            sourceSum += s.charAt(i);
            targetSum += t.charAt(i);
            i++;
        }

        if (i < s.length()) {
            for (int j = i; j < s.length(); j++) {
                sourceSum += s.charAt(j);
            }
        } else {
            for (int j = i; j < t.length(); j++) {
                targetSum += t.charAt(j);
            }
        }

        return (char) Math.abs(targetSum - sourceSum);
    }
}
